name: Unit Tests

on:
  push:

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        test:
          - name: "Unit tests (lib)"
            command: go test ./lib/...
          # E2E tests don't work on github actions

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'
          check-latest: true

      - uses: FedericoCarboni/setup-ffmpeg@37062fbf7149fc5578d6c57e08aed62458b375d6
        id: setup-ffmpeg

      - name: Run the test
        run: ${{ matrix.test.command }}
